---
title: "Untitled"
output: html_document
---

##
When you 

```{r cars}
library(tidyverse)

model_name <- "pickup"

mpg <- mpg

#this is a comment
models <-
    mpg %>% #this is another comment
    mutate(model_new = ifelse(str_detect(model, model_name), 
                          model_name, 
                          str_extract(model, "\\w+"))) %>% 
    filter(year == 1999) %>% 
    group_by(model_new) %>% 
    count(sort = T) %>% 
    ungroup()

over_5 <- function(x) {
    x > 5
}

for(i in 1:nrow(models)) {
     print(models$n[i] %% 3)
}

models$over_5 <- over_5(models$n)

edit_models <-
    models %>% 
    mutate(over_10 = over_5(n/2))

#p <- paste0("here is one string of text", fn, "another string of text")

make_list <- 
    list(edit_models$model_new,
         c(1999, 2000),
         TRUE)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
